version: '3.8'

services:
  backend:
    build: .
    container_name: intelliquery
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - prisma_migrate

  prisma_migrate:
    image: node:18
    container_name: prisma_migrate
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "npm install && npx prisma migrate deploy"
    env_file:
      - .env

